#include "git_version.h"
// git_version.cpp is auto-generated by ci/pio_git_version.py on every build

const char *git_hash = "be81114";
const char *git_time = "2026-06-02T00:47:12+02:00";
const char *git_tag = "";
