#include "git_version.h"
// git_version.cpp is auto-generated by ci/pio_git_version.py on every build

const char *git_hash = "efd0b0b";
const char *git_time = "2026-05-11T23:02:40+02:00";
const char *git_tag = "";
