#include "git_version.h"
// git_version.cpp is auto-generated by ci/pio_git_version.py on every build

const char *git_hash = "8c8222a";
const char *git_time = "2026-05-24T22:49:29+02:00";
const char *git_tag = "";
